# Generated by Django 5.2 on 2025-11-10 07:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_cart_unique_together_payment_orderplaced'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderPlaced',
            new_name='Order',
        ),
    ]
