# Generated by Django 5.2 on 2026-04-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payer_email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paypal_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paypal_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paypal_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(default='montonio', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
