# Generated by Django 5.2 on 2026-04-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_payment_payer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paypal_order_id',
        ),
    ]
