# Generated by Django 5.2 on 2026-04-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_payment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cart_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
