### Review test
POST http://localhost:8002/notify/
Content-Type: application/json

{
  "event_type": "review",
  "data": {
    "product_name": "Cookies",
    "username": "Santa",
    "rating": 5,
    "comment": "Nice!"
  }
}

### Payment test
POST http://localhost:8002/notify/
Content-Type: application/json

{
  "event_type": "payment",
  "data": {
    "order_id": "ORDER-1",
    "username": "Anna",
    "amount": 100
  }
}

### Stock test
POST http://localhost:8002/notify/
Content-Type: application/json

{
  "event_type": "stock",
  "data": {
    "product_name": "Apples",
    "quantity": 3
  }
}