"""
Django settings for onlineshop project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "fallback-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

#ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'kasi-postthyroidal-monopoly.ngrok-free.dev']

# if DEBUG:
#     # Automatically allow any ngrok domain
#     ngrok_pattern = re.compile(r'.*\.ngrok-free\.dev$')

#     ALLOWED_HOSTS = ['localhost', '127.0.0.1']
#     CSRF_TRUSTED_ORIGINS = []

#     # Check if an NGROK_URL env var exists
#     NGROK_URL = os.environ.get('NGROK_URL')
#     if NGROK_URL:
#         # Strip trailing slashes
#         NGROK_URL = NGROK_URL.rstrip('/')
#         # Extract hostname
#         host = NGROK_URL.split('://')[-1]
#         ALLOWED_HOSTS.append(host)
#         CSRF_TRUSTED_ORIGINS.append(f'https://{host}')

#     # Optional: allow wildcard for any ngrok-free.dev subdomain
#     ALLOWED_HOSTS.append('.ngrok-free.dev')
#     CSRF_TRUSTED_ORIGINS.append('https://*.ngrok-free.dev')
# else:
#     # Production settings
#     ALLOWED_HOSTS = ['your-production-domain.com']
#     CSRF_TRUSTED_ORIGINS = ['https://your-production-domain.com']

if DEBUG:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'kasi-postthyroidal-monopoly.ngrok-free.dev']
else:
    ALLOWED_HOSTS = ['zaneagroshop.eu.pythonanywhere.com']

CSRF_TRUSTED_ORIGINS = [
    'https://zaneagroshop.eu.pythonanywhere.com',
    'https://kasi-postthyroidal-monopoly.ngrok-free.dev',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'rest_framework',
    'api',
    'payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'onlineshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.cart_item_count',
                'app.context_processors.wishlist_item_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'onlineshop.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
LOGIN_REDIRECT_URL = '/profile/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration for real email sending (e.g., Gmail SMTP)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')            # App Password generated from Google Account
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
ADMIN_EMAIL = "zane.gaiduka@gmail.com"

# Montonio API credentials

MONTONIO_ACCESS_KEY = os.getenv("MONTONIO_ACCESS_KEY")
MONTONIO_SECRET_KEY = os.getenv("MONTONIO_SECRET_KEY")
MONTONIO_BASE_URL = "https://sandbox-stargate.montonio.com/api"
MONTONIO_SANDBOX = True  # Switch to False for production

print("ACCESS:", os.getenv("MONTONIO_ACCESS_KEY"))

if DEBUG:
    BASE_URL = os.getenv("NGROK_URL")
else:
    BASE_URL = "https://zaneagroshop.eu.pythonanywhere.com"

MONTONIO_RETURN_URL = f"{BASE_URL}/payment-success/"
MONTONIO_NOTIFICATION_URL = f"{BASE_URL}/montonio/webhook/"

# API base URLs
if MONTONIO_SANDBOX:
    MONTONIO_API_BASE = "https://sandbox-stargate.montonio.com/api"
else:
    MONTONIO_API_BASE = "https://api.montonio.com"




